### ISSUE TITLE
.Net Coreify NSpec like all the cool kids

### ISSUE THREAD

**Issue by amirrajan** [mattflo/NSpec#129]
Discuss!

**Comment by BrainCrumbz** [comment]
Definitely. Opening such an issue was on our list.

Possible steps:

1. Confirm current working state of NUnit on netstandard Net 4.6 / Net Core 1.0. So that we know we can port NSpecSpecs. This should be already a green flag.
1. Confirm current state of technologies currently used by NSpec (reflection, marshaling, ...) on netstandard Net 4.6 / Net Core 1.0. This could be done by looking at other libraries like Fixies. Or also by just trying next item and see if it builds.
1. Switch NSpec class library, NSpecSpecs, NSpec console runner to netstandard Net 4.6 build
1. Switch NSpec class library, NSpecSpecs, NSpec console runner to netstandard Core 1.0 build

Then, for test runners:

1. Understand API & protocol for working with `dotnet test`. There are some sparse docs now, plus work done by xUnit, NUnit.
1. If current VS test runner still has reasons to exist (e.g. for non-netstandard client code, don't know, or for older VS versions), split that in a *core* part, generic, and an *adapter* part specific to VS test runner
1. Create dotnet test runner, reusing previous *core* part

Just thrown there, not necessarily a plan. Let's see what actually makes sense.

**Comment by amirrajan** [comment]
The biggest thing would be the App Domain code (mostly half baked as is). We had that discussion here: https://github.com/mattflo/NSpec/issues/105

**Comment by BrainCrumbz** [comment]
It looks like that path could work when code under test is in a class library, and anyway when you can reference it from a custom console app that acts as your custom test runner. 

It completely leaves out former VS Test Adapter scenario, as well as current *dotnet test* scenario that seems to be "the way forward" (for console, not sure if that also replaces VS Test Adapter for future VS versions).

**Comment by amirrajan** [comment]
>for console, not sure if that also replaces VS Test Adapter for future VS versions

I'd imagine future integrations would build off of `dotnet test`. That and VS Code is entirely electron/not vsix stuff.

**Comment by BrainCrumbz** [comment]
BTW currently taking a stab at make it build & run on .NET Core. Current status:

1. NSpec class library updated to build
1. NSpecRunner console app not building yet. 

Of course main issue there is the AppDomain / Marshaling technology. In test runners/adapters scenarios (that is, when you cannot put up a custom console app and reference project under test) one still needs some way of executing code across two assemblies: the runner assembly and the assembly under test.

At a first look this should be needed by other testing frameworks as well, e.g. NUnit, so I'd say taking a look at those should be helpful. Or maybe directly asking as well. What do you think?

**Comment by BrainCrumbz** [comment]
E.g. see excerpt from [this comment](https://github.com/nunit/nunit/issues/1371#issuecomment-200346080) on NUnit:

> The first step in this process was creating a PCL driver/agent that can load and execute tests without being tightly bound to a specific version of the NUnit Framework like NUnitLite and the current Xamarin runner. It is still in it's infancy, but the work in progress is in the nunit.portable.agent project.

That last project as move since, [this](https://github.com/nunit/nunit.portable.agent) is the current link

**Comment by BrainCrumbz** [comment]
Some insights after a quick inspection:

1. Their dotnet test console runner (net core) depends on portable agent (net core). Don't know about other existing runners, like VS test runner, plain console runner, GUI runner

1. Portable agent does not depend on any NUnit framework library, but still is the *driver* used by other runners to operate with the framework

1. Portable agent dinamically loads at runtime the NUnit assembly (exists in several net flavours) that comes linked together with the assembly under test

1. Portable agent instantiates through reflection a specific class from NUnit assembly and can invoke its methods to perform a set of commands. Methods parameters and return values are all primitive types or `Action`s on primitive types. Complex data structures are *"hidden"* in text parameters as XML.

1. Such class with its methods is a façade to the operation allowed from the outside, and is basically the API to work with test framework. Actually, also the XML data structure is an implicit part of the API

1. The actual core work happens within the NUnit assembly where the façade class is defined. This approach should be what eliminates the need for .NET Remoting technologies (*MarshalByRef* and all that family), as code is already defined and runs in the same assembly (the one under test) as opposed to being defined in runner and having to execute in assembly under test.

It seems like a similar approach could be taken for NSpec as well, and it could also start with refactorings in the solution as is now on .NET platform, without switching yet to .NET Core.

@amirrajan waiting for your feedbacks!

**Comment by amirrajan** [comment]
Any thoughts of "downgrading" nspec specs to just be a console app that throws exceptions? Or something even more terrifying. Use NSpec to test NSpec?

**Comment by BrainCrumbz** [comment]
We can test NSpec pretty much any way you want :smile_cat: , so I guess potentially even with a custom console app or self-testing it. But I don't see how this could help, sorry. The whole point is to be able to test newly created .Net Core projects with NSpec, beside NSpec itself I mean. 

Right now in my team we already have a couple of project started on (ASP).Net Core, and we're pulling to test with NSpec because that's not available yet. If .Net Core becomes *the* (or *a*) way to go in .Net world, why leave NSpec behind?

**Comment by amirrajan** [comment]
> The whole point is to be able to test newly created .Net Core projects with NSpec, beside NSpec itself I mean.

Sorry for the confusion. I was thinking that NSpec could be entirely built using .Net Core. If the only thing stoping the NSpec solution from moving to .Net core is NUnit, then our own NSpecSpecs test suite can be written in something compatible.

**Comment by BrainCrumbz** [comment]
> I was thinking that NSpec could be entirely built using .Net Core. 
That's what I meant as well :+1: I think we should aim to build NSpec both for previous .Net plarform as well as .Net Core. To obtain this result, I assume the whole solution should be moved to the new VS 2015 / .Net Core / project.json tooling (even if the project.json should go away in the future): that allows to build a version for .Net Core, and if we add another target also for previous .Net. Otherwise, keep two solutions: one as-is targeting only previous .Net, plus a new one targeting .Net Core, but if we can get everything with one solution ...

> If the only thing stoping the NSpec solution from moving to .Net core is NUnit
No, NUnit is actually already ready for .Net Core, so if at some point we have NSpec built for .Net Core, we can port also NSpecSpecs test suite to .Net Core, using the most recent version of NUnit

It looks like a conf-call would help cleaning a little bit, what do you think?

**Comment by amirrajan** [comment]
>To obtain this result, I assume the whole solution should be moved to the new VS 2015 / .Net Core / project.json tooling

Seems like a good first step!

**Comment by amirrajan** [comment]
>It looks like a conf-call would help cleaning a little bit, what do you think?

Introvert here :-P. G+ works if you need a faster response (ar@amirrajan.net). We can do Skype or something too if you insist. But I'm gonna expect like a free lunch or something if you ever come to Dallas.

**Comment by BrainCrumbz** [comment]
Well, speaking about eating, nothing bad for Dallas, but I guess you better come over here in Italy ;) It is just for a faster response, I think G+ would do once we manage with our timezones

**Comment by BrainCrumbz** [comment]
[This is](https://github.com/BrainCrumbz/NSpec.NetCore) a temporary repository, to track how initial work and see how it goes. There should be an invitation in your mailbox too

**Comment by BrainCrumbz** [comment]
[Here's](https://github.com/BrainCrumbz/NSpec.NetCore/issues/1) an update with current activities. BTW, this now works from command line:

```bash
dotnet path_to\NSpecRunner.dll path_to_spec_dll [classname]
```

**Comment by BrainCrumbz** [comment]
Closing this issue, progress can be tracked in #143
